filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
build:
    tests:
        override:
            -
                command: 'tools/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'
    dependencies:
            before:
                - 'wget https://phar.io/releases/phive.phar'
                - 'php phive.phar install --trust-gpg-keys 4AA394086372C20A'
    environment:
        php:
            version: 7.0.7